### ISSUE TITLE
如何实现回调功能

### ISSUE THREAD

**Issue by ctbsea** [shitingbao/socketio-go-redis-adapter#1]
Listener func(...any)
没有返回参数
怎么实现如下的回调功能

```
server.On("some:event", func(msg string) string {
 //Sending ack with data in msg back to client, using "return statement"
 return msg
})
```

**Comment by shitingbao** [comment]
sir, since the original project has been refactored, the support of this project may not continue. It is only used for some learning reference. If you are interested, you can copy it and develop it yourself. Thank you for your attention. you can see Example Code
